avatar_size: 1024
user:
  minimum_coin: 0
  minimum_number_free: 0
  maxnimum_number_free: 3
  maxnimum_number_dowload: 10
  add_number_upload: 1
  minus_total_coin: 10
  minus_number_free: 1
  default_total_coin: 0
  name_length: 50
  email_length: 255
  password_length: 6
  remember_me: "1"
coin:
document:

