user:
  minimum_coin: 0
  minimum_number_free: 0
  maxnimum_number_free: 3
  maxnimum_number_dowload: 10
  add_number_upload: 1
  minus_total_coin: 10
  minus_number_free: 1
  default_total_coin: 0
coin:

document:
