avatar_size: 1024
paginate_number: 4
active: "active"
user:
  minimum_coin: 0
  minimum_number_free: 0
  minimum_number_upload: 0
  maxnimum_number_free: 3
  maxnimum_number_dowload: 10
  add_number_upload: 1
  minus_total_coin: 10
  minus_number_free: 1
  default_total_coin: 0
  name_length: 50
  email_length: 255
  password_length: 6
  remember_me: "1"
coin:
document:
  name_length: 5
  name_max_length: 200
  description_length: 4
friend:
  request: 0
  accept: 1
  paginate_number: 8
like:
  flag_like: "like"
  flag_unlike: "unlike"
history:
  action_upload: "upload"
  action_download: "download"
payment:
  not_pay: "No Pay"
  pay: "Pay"
  cancel: "Cancel"
  staus_no_pay: 0
